language: python
env:
  - PYCRYPTO_VERSION=2.4.1
  - PYCRYPTO_VERSION=2.6.1
python:
  - "2.6"
  - "2.7"

before_install:
  # install extension using apt-get to save compiling
  # NB: Travis-CI uses Ubuntu 12.04 TLS, thus these are only available
  #     for Python 2.7.
  - sudo apt-get update -qq
  - sudo apt-get install -y python-gst0.10
  - sudo apt-get install -y python-imaging
  - sudo apt-get install -y python-matplotlib
  - sudo apt-get install -y python-mysqldb
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-pyodbc
  - sudo apt-get install -y python-qt4
  - sudo apt-get install -y python-scipy
  - sudo apt-get install -y python-wxgtk2.8
  # fix a problem in travis, see
  # https://github.com/travis-ci/travis-ci/issues/3106
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  - sudo apt-get install -y python-zmq
  - sudo apt-get install -y libespeak1  # required by pyttsx

install:
  # now install the package itself
  - pip install -e .

  # install pure-python packages (requires PyInstaller to be installed)
  - python tests/setupenv_unix.py

script:
  - cd tests
  - ./runtests.py
  - ./runtests.py --all-with-crypto basic/*.py
